[package]
name = "aniworld"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", default-features = false, features = ["derive", "std", "help", "usage"] }
indexmap = { version = "2.11.0", default-features = false, features = ["serde"] }
once_cell = { version = "1.21.3", default-features = false }
regex = { version = "1.11.2", default-features = false, features = ["unicode-perl"] }
reqwest = { version = "0.12.23", default-features = false, features = ["blocking", "default-tls"] }
scraper = { version = "0.24.0", default-features = false }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.143", default-features = false, features = ["alloc"] }
