from aniworld.models import MegaKinoEpisode

test_url = "https://megakino8.com/films/205-deadpool.html"
movie = MegaKinoEpisode(test_url)

print("Title:", movie.title)
print("Cleaned Title:", movie.title_cleaned)
print("Original Title:", movie.original_title)
print("Description:", movie.description)
print("Genres:", movie.genres)
print("Country:", movie.country)
print("Release Year:", movie.release_year)
print("Duration (minutes):", movie.duration_minutes)
print("Poster URL:", movie.poster_url)
print("Backdrop URL:", movie.backdrop_url)
print("Directors:", movie.directors)
print("Actors:", movie.actors)
print("Producer:", movie.producer)
print("Age Rating:", movie.age_rating)
print("Quality Label:", movie.quality_label)
print("Kinopoisk Rating:", movie.kinopoisk_rating)
print("Site Rating Score:", movie.site_rating_score)
print("Site Rating Votes:", movie.site_rating_votes)
print("Likes:", movie.likes)
print("Dislikes:", movie.dislikes)
print("Trailer URL:", movie.trailer_url)
print("Post ID:", movie.post_id)
print("Canonical URL:", movie.canonical_url)
print("OG Image URL:", movie.og_image)
print("Created At:", movie.created_at)
print("Published At:", movie.published_at)
print("Player Sources:", movie.player_sources)
print("Default Player:", movie.default_player)
print("Stream Label:", movie.stream_label)
print("Available Hosts:", movie.available_hosts)
print("Recommended Entries:")
for entry in movie.recommended_entries or []:
    print(entry)

# movie.download()
